Data.chromeFonts = [
    "Abyssinica SIL",
    "Bitstream Vera Sans",
    "C059",
    "Cantarell",
    "Comfortaa",
    "D050000L",
    "DejaVu Sans",
    "DejaVu Sans Mono",
    "DejaVu Serif",
    "Droid Sans",
    "Fira Code",
    "FreeMono",
    "FreeSans",
    "FreeSerif",
    "Jomolhari",
    "Khmer OS",
    "Khmer OS Content",
    "Khmer OS System",
    "Liberation Mono",
    "Liberation Sans",
    "Liberation Serif",
    "Lohit Assamese",
    "Lohit Bengali",
    "Lohit Devanagari",
    "Lohit Gujarati",
    "Lohit Gurmukhi",
    "Lohit Kannada",
    "Lohit Odia",
    "Lohit Tamil",
    "Lohit Telugu",
    "Meera",
    "Mingzat",
    "Monospace",
    "Montserrat",
    "Nimbus Mono PS",
    "Nimbus Roman",
    "Nimbus Sans",
    "Nimbus Sans Narrow",
    "Noto Color Emoji",
    "Noto Sans CJK HK",
    "Noto Sans CJK JP",
    "Noto Sans CJK KR",
    "Noto Sans CJK SC",
    "Noto Sans CJK TC",
    "Noto Sans Mono CJK HK",
    "Noto Sans Mono CJK JP",
    "Noto Sans Mono CJK KR",
    "Noto Sans Mono CJK SC",
    "Noto Sans Mono CJK TC",
    "Noto Sans Sinhala",
    "Noto Serif CJK JP",
    "Noto Serif CJK KR",
    "Noto Serif CJK SC",
    "Noto Serif CJK TC",
    "Nuosu SIL",
    "P052",
    "PT Sans",
    "PT Sans Narrow",
    "Padauk",
    "PakType Naskh Basic",
    "STIX",
    "Sans",
    "Serif",
    "Source Code Pro",
    "URW Bookman",
    "URW Gothic",
    "Waree",
    "Wingdings 2",
    "Z003",
    "cmex10",
    "cmmi10",
    "cmr10",
    "cmsy10",
    "esint10",
    "eufm10",
    "msam10",
    "msbm10",
    "rsfs10",
    "stmary10",
    "wasy10",
]